colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Blog.Connect365
layout_spectrum: 0.4775861157104373
typography_spectrum: 0.04336069384589791
color:
  brandStrength: 0.7358665091451257
  lightness: 0.4794207268860191
  saturation: 0.07100858609192073
  rhythmicContrast: 0.24650313542224467
  brandColors:
    - '#F6F792'
    - '#333745'
    - '#77C4D3'
    - '#DAEDE2'
    - '#EA2E49'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FOvj3gZ-DwcU%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DOvj3gZ-DwcU&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FOvj3gZ-DwcU%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: CONNECT/Tržišne komunikacije
          url: 'https://www.youtube.com/channel/UCt4YJ5o5gdsfSgRadQ_o05Q'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - naslovna
        - strana
        - duration
        - views
        - nikola
        - kviz
        - pavlovic
        - svet
        - mori
        - rouzin
      description: Uploaded by CONNECT/Tržišne komunikacije on 2017-03-08.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=Ovj3gZ-DwcU&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=Ovj3gZ-DwcU&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=Ovj3gZ-DwcU&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=Ovj3gZ-DwcU&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=Ovj3gZ-DwcU&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=Ovj3gZ-DwcU'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=Ovj3gZ-DwcU
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=Ovj3gZ-DwcU
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/Ovj3gZ-DwcU'
      title: Naslovna
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
url: 'http://blog.connect365.online'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1b0cb3d-2fd0-41dd-81b8-75cf0bfadbb6.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d80e30b9-539a-4db7-b6ed-706e556c284a.png
title: Pratite korisne informacije
description: Ovo su tekstovi koje pišemo iz naše iskustva
purpose:
  - type: external
    url: 'http://www.subscribepage.com/b8c7z2'
    label: Pretplati se
analytics:
  google: UA-19682937-18
